# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = AvisClient.o Chaine.o Chambre.o Clients.o Date.o Facture.o Hotel.o Main.o Nourritures.o Reservation.o
LINKOBJ  = AvisClient.o Chaine.o Chambre.o Clients.o Date.o Facture.o Hotel.o Main.o Nourritures.o Reservation.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

AvisClient.o: AvisClient.c
	$(CC) -c AvisClient.c -o AvisClient.o $(CFLAGS)

Chaine.o: Chaine.c
	$(CC) -c Chaine.c -o Chaine.o $(CFLAGS)

Chambre.o: Chambre.c
	$(CC) -c Chambre.c -o Chambre.o $(CFLAGS)

Clients.o: Clients.c
	$(CC) -c Clients.c -o Clients.o $(CFLAGS)

Date.o: Date.c
	$(CC) -c Date.c -o Date.o $(CFLAGS)

Facture.o: Facture.c
	$(CC) -c Facture.c -o Facture.o $(CFLAGS)

Hotel.o: Hotel.c
	$(CC) -c Hotel.c -o Hotel.o $(CFLAGS)

Main.o: Main.c
	$(CC) -c Main.c -o Main.o $(CFLAGS)

Nourritures.o: Nourritures.c
	$(CC) -c Nourritures.c -o Nourritures.o $(CFLAGS)

Reservation.o: Reservation.c
	$(CC) -c Reservation.c -o Reservation.o $(CFLAGS)
